### ISSUE TITLE
" Parse error: Invalid numeric constant at 'b' "

### ISSUE THREAD

**Issue by fenix-hub** [jellehermsen/gdunzip#3]
Hi, I'm trying to use your plugin in Godot Engine 3.2beta1 to implement it inside one of my plugins.
Currently I'm having some problems integrating your code, and since I don't want to mess it up I'll just share with you what is the issue right now.

![zip1](https://user-images.githubusercontent.com/45271396/69466900-2d006200-0d86-11ea-990c-a41d7104f57b.PNG)

**Comment by jellehermsen** [comment]
Thanks for opening the issue! I haven't yet tested in 3.2, but I will check it out.

**Comment by jellehermsen** [comment]
The issue seems to be that Godot 3.2beta1 requires hexadecimal constants to be all uppercase (everything behind the "0x" that is). I have modified all literals in the code and ran the tests using the latest beta snapshot and they all worked fine. You can pull the latest version version of the master branch and that should work fine.
